baseURL: "https://stonebirdjx.github.io/"
title: "石鸟路遇"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: StoneBird
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: "StoneBird"
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  editPost:
    URL: "https://github.com/stonebirdjx/stonebirdjx.github.io/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
  cover:
    responsiveImages: false
    linkFullImages: true
  disableThemeToggle: false
  

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/img/favicon_bird.png"
    favicon16x16: "/img/favicon_bird.png"
    favicon32x32: "/img/favicon_bird.png"
    apple_touch_icon: "/img/favicon_bird.png"
    safari_pinned_tab: "/img/favicon_bird.png"

  label:
    text: "StoneBird"
    icon: /img/hi.png
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "石鸟路遇"
    Content: |
      欢迎来到我的blog，我是石鸟路遇(stonebirdjx)，一名优秀与善良并存的软件开发工程师，热爱生活、热爱学习、善于观察、善于记录。

      Simple, Poetic, Pithy

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary


  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: email
      url: "mailto:1245863260@qq.com"
    - name: github
      url: "https://github.com/stonebirdjx"

menu:
  main:
    - identifier: Search
      name: Search
      url: /search/
      weight: 10
    - identifier: Archive
      name: Archive
      url: /archives/
      weight: 10
    - identifier: Tags
      name: Tags
      url: /tags/
      weight: 10

